### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

spring:
  profiles.active: default
---
spring:
  profiles: default   # this is for local development. For QA, Production override these values

spring.jmx:
   enabled: false

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL

server:
  port: 8090



#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: spring-boot-rest-example
  version: 0.1
  description: boot-example default description
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

git:
  localRepo: './powershell-status-scripts/'
  remoteRepo: 'https://github.com/brianaddicks/SendashScripts.git'
  
# LOGGING
logging:
  path: /var/log
  file: sendash.log
  level.org.hibernate.SQL: DEBUG
---
spring:
  profiles: test

spring.jpa:
    hibernate.ddl-auto: create-drop #validate

git:
  localRepo: './powershell-status-scripts/'
  remoteRepo: 'https://github.com/brianaddicks/SendashScripts.git'

flyway:
  driver:  org.h2.Driver
  url:  jdbc:h2:mem:bootexample;MODE=MySQL
  appUser:  h2_test
  password:  h2_test
  locations: sampletest3



