### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

spring:
  profiles.active: default
---
spring:
  profiles: default   # this is for local development. For QA, Production override these values

spring.jmx:
   enabled: false

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:sendash;
    
spring.jpa:
  hibernate.ddl-auto: none

server:
  port: 8090


#todo: make sure to always enable security in production
security:
  user:
    password: 123456

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: spring-boot-rest-example
  version: 0.1
  description: boot-example default description
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

git:
  localRepo: '~/powershell-status-scripts/'
  zipOfRep: '~/sendash.zip'
  remoteRepo: 'https://github.com/brianaddicks/SendashScripts.git'

  
# LOGGING
logging:
  path: /var/log/sendash
  file: sendash.log
  level.org.hibernate.SQL: WARN
  org.springframework.security: DEBUG

---
spring:
  profiles: dev
  
spring.jpa:
   hibernate.ddl-auto: none

spring.datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:sendash;MODE=MySQL;
  
git:
  localRepo: './powershell-status-scripts/'
  zipOfRep: './sendash.zip'
  remoteRepo: 'https://github.com/brianaddicks/SendashScripts.git'

---
spring:
  profiles: test

spring.jpa:
    hibernate.ddl-auto: validate
    show-sql: true

git:
  localRepo: './powershell-status-scripts/'
  zipOfRep: './sendash.zip'
  remoteRepo: 'https://github.com/brianaddicks/SendashScripts.git'
  

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:sendash;DB_CLOSE_DELAY=-1;
    schemas: PUBLIC

flyway:
  driver:  org.h2.Driver
  url: jdbc:h2:mem:sendash;DB_CLOSE_DELAY=-1;
  appUser:  sa
  schemas: PUBLIC
  
---
spring:
  profiles: MicroserviceIntegrationTests

spring.jpa:
    hibernate.ddl-auto: validate
    show-sql: true

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:sendash;DB_CLOSE_DELAY=-1;
    schemas: PUBLIC

flyway:
  driver:  org.h2.Driver
  url: jdbc:h2:mem:sendash;DB_CLOSE_DELAY=-1;
  appUser:  sa
  schemas: PUBLIC  


server:
  port: 8181

