spring:
  profiles.active: dev
---
spring:
  profiles: dev

  
logging:
  path: /var/log/sendash
  file: sendashEmailer.log
  
server:
  port: 8090
---
spring:
  profiles: production
  
server:
  port: 8090
  
  