CREATE table USER_CLIENT(
    CLIENT_ID BIGINT NOT Null,
    USER_ID BIGINT NOT Null,
    PRIMARY KEY(CLIENT_ID, USER_ID),
    FOREIGN KEY (CLIENT_ID)
        REFERENCES Client(ID),
    FOREIGN KEY (USER_ID)
    	REFERENCES PERSON(ID)
)ENGINE=InnoDB;

CREATE INDEX UserClientClientId
    ON USER_CLIENT(CLIENT_ID);
 
CREATE INDEX UserClientUserId
    ON USER_CLIENT(USER_ID);
    
INSERT INTO USER_CLIENT (CLIENT_ID, USER_ID) VALUES(1,1);