CREATE TABLE ROLE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME varchar(255) NOT NULL,
	PRIMARY KEY(ID)
);

INSERT INTO ROLE(ID, NAME) VALUES(1, 'ROLE_USER');
INSERT INTO ROLE(ID, NAME) VALUES(2, 'ROLE_ADMIN');



