CREATE table USER_ROLE(
    USER_ID BIGINT NOT Null AUTO_INCREMENT,
    ROLE_ID BIGINT NOT Null,
    PRIMARY KEY(USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID)
        REFERENCES PERSON(ID),
    FOREIGN KEY (ROLE_ID)
        REFERENCES ROLE(ID)
);

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES(1,1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES(1,2);
