CREATE TABLE PERSON (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	UUID BINARY(16) NOT NULL UNIQUE,
	EMAIL varchar(255) UNIQUE,
	PASSWORD varchar(255) NOT NULL,
	FIRST_NAME varchar(255) NOT NULL,
	LAST_NAME varchar(255) NOT NULL,
	PRIMARY KEY(ID)
) ENGINE=InnoDB;

CREATE INDEX personId
    ON PERSON(EMAIL);
    
CREATE INDEX personUuid
  	ON PERSON(UUID);