CREATE TABLE PERSON (
	ID BIGINT NOT NULL PRIMARY_KEY AUTO_INCREMENT,
	EMAIL varchar(255),
	FIRST_NAME varchar(255) NOT NULL,
	LAST_NAME varchar(255) NOT NULL,
);

CREATE INDEX personId
    ON Person(EMAIL);