CREATE table EndPoint(
    ID VARCHAR(36) NOT Null,
    CLIENT_ID VARCHAR(36) NOT Null,
    HOST_NAME varchar(255),
    API_KEY varchar(255) UNIQUE,
    UPDATE_SCRIPT_REQUEST DATETIME,
    PRIMARY KEY(CLIENT_ID, HOST_NAME),
    FOREIGN KEY (CLIENT_ID)
        REFERENCES Client(ID)
);

CREATE INDEX endPointId
    ON EndPoint(ID);

CREATE INDEX endPointApiAndClientId
    ON EndPoint(CLIENT_ID, API_KEY);