CREATE TABLE Payload (
	ID INTEGER NOT Null AUTO_INCREMENT,
	RECEIVED_TIMESTAMP DATETIME NOT NULL,
	REF varchar(255),
	BEFORE varchar(255),
    AFTER varchar(255),
	PRIMARY KEY (ID)
);


CREATE INDEX payloadTime
    ON Payload(RECEIVED_TIMESTAMP);

