CREATE TABLE Commit (
	ID BIGINT NOT Null AUTO_INCREMENT,
	PAYLOAD_ID INTEGER Not Null,
	MESSAGE varchar(255),
	COMMIT_DATE TIMESTAMP NOT NULL,
	ADDED varchar(255),
	MODIFIED varchar(255),
    REMOVED varchar(255),
	PRIMARY KEY (MESSAGE, COMMIT_DATE),
 	FOREIGN KEY (PAYLOAD_ID)
		REFERENCES Payload(ID)

);

CREATE INDEX COMMIT_ID
    ON Commit(ID);
CREATE INDEX COMMIT_PAYLOAD
    ON Commit(PAYLOAD_ID);

    
CREATE TABLE ADD_SCRIPT_COMMITS (
  	COMMIT_ID BIGINT NOT NULL, 
  	SCRIPT_NAME varchar(255) NOT NULL,
  	PRIMARY KEY (COMMIT_ID, SCRIPT_NAME),
  	FOREIGN KEY (COMMIT_ID)
  		REFERENCES Commit(ID)
);

CREATE TABLE MODIFIED_SCRIPT_COMMITS (
  	COMMIT_ID BIGINT NOT NULL, 
  	SCRIPT_NAME varchar(255) NOT NULL,
  	PRIMARY KEY (COMMIT_ID, SCRIPT_NAME),
  	FOREIGN KEY (COMMIT_ID)
  		REFERENCES Commit(ID)
);

CREATE TABLE REMOVED_SCRIPT_COMMITS (
  	COMMIT_ID BIGINT NOT NULL, 
  	SCRIPT_NAME varchar(255) NOT NULL,
  	PRIMARY KEY (COMMIT_ID, SCRIPT_NAME),
  	FOREIGN KEY (COMMIT_ID)
  		REFERENCES Commit(ID)
);
