CREATE TABLE Commit (
	ID INT NOT Null AUTO_INCREMENT,
	PAYLOAD_ID INTEGER Not Null,
	MESSAGE varchar(255),
	COMMIT_DATE TIMESTAMP NOT NULL,
	ADDED varchar(255),
	MODIFIED varchar(255),
    REMOVED varchar(255),
	PRIMARY KEY (MESSAGE, COMMIT_DATE),
 	FOREIGN KEY (PAYLOAD_ID)
		REFERENCES Payload(ID)

);

CREATE INDEX COMMIT_ID
    ON Commit(ID);
CREATE INDEX COMMIT_PAYLOAD
    ON Commit(PAYLOAD_ID);
